name: release
permissions:
  contents: write
on:
  release:
    types: [published]
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install pnpm
        uses: pnpm/action-setup@v2
      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: pnpm
      - name: Setup
        run: npm i -g @antfu/ni
      - name: Generate Changelog
        run: nr changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  wait:
    runs-on: ubuntu-latest
    needs: changelog
    steps:
      - name: Wait for checks to succeed
        uses: poseidon/wait-for-status-checks@v0.4.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          interval: 5

  dist:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            code-target: win32-x64
          - os: windows-latest
            target: aarch64-pc-windows-msvc
            code-target: win32-arm64
          - os: ubuntu-20.04
            target: x86_64-unknown-linux-gnu
            code-target: linux-x64
          - os: ubuntu-20.04
            target: aarch64-unknown-linux-gnu
            code-target: linux-arm64
          - os: ubuntu-20.04
            target: arm-unknown-linux-gnueabihf
            code-target: linux-armhf
          - os: macos-latest
            target: x86_64-apple-darwin
            code-target: darwin-x64
          - os: macos-latest
            target: aarch64-apple-darwin
            code-target: darwin-arm64
    name: dist (${{ matrix.target }})
    runs-on: ${{ matrix.os }}
    needs: wait
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
      - uses: Swatinem/rust-cache@v2
      - name: Update apt repositories (linux)
        if: matrix.target == 'aarch64-unknown-linux-gnu' || matrix.target == 'arm-unknown-linux-gnueabihf'
        run: sudo apt-get update
      - name: Install GCC arm64 (linux)
        if: matrix.target == 'aarch64-unknown-linux-gnu'
        run: sudo apt-get install gcc-aarch64-linux-gnu
      - name: Install GCC armhf (linux)
        if: matrix.target == 'arm-unknown-linux-gnueabihf'
        run: sudo apt-get install gcc-arm-linux-gnueabihf
      - run: cargo build --target ${{ matrix.target }} --release
      - name: Install pnpm
        uses: pnpm/action-setup@v2
      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: pnpm
      - name: Setup
        run: npm i -g @antfu/ni
      - name: Install
        run: nci
      - name: vsce package
        shell: bash
        run: |
          mkdir -p bundled dist
          cp target/${{ matrix.target }}/release/typed-key* bundled/
          nr vsce package -o dist/ --target ${{ matrix.code-target }}
      - name: Archive
        shell: bash
        run: |
          ver=${GITHUB_REF/refs\/*\//}
          archive="typed-key-$ver-${{ matrix.target }}"
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            7z a "dist/${archive}.zip" target/${{ matrix.target }}/release/typed-key.exe
          else
            tar czf "dist/${archive}.tar.gz" -C target/${{ matrix.target }}/release typed-key
          fi
          ls -al dist/*
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}
          path: dist

  publish:
    runs-on: ubuntu-latest
    needs: dist
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          path: dist
      - name: Install pnpm
        uses: pnpm/action-setup@v2
      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: pnpm
      - name: Setup
        run: npm i -g @antfu/ni
      - name: Install
        run: nci
      - name: Inspect dist
        run: |
          ls -al dist/*
          nr glob dist/**/*.vsix
      - name: vsce publish
        run: nr vsce publish --packagePath $(nr glob dist/**/*.vsix)
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
      - name: ovsx publish
        run: nr ovsx publish --packagePath $(nr glob dist/**/*.vsix)
        env:
          OVSX_PAT: ${{ secrets.OVSX_PAT }}
      - name: Upload to GH release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: dist/**/*
