name: Create Release
on:
  push:
    branches:
      - main
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.7.1

      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Get current version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: Bump version
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          npm version patch
          git push
          git push --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get new version
        id: new-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: Generate Changelog
        run: npx changelogithub --from v${{ steps.package-version.outputs.current-version }} --to v${{ steps.new-version.outputs.current-version }}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.new-version.outputs.current-version }}
          release_name: Release v${{ steps.new-version.outputs.current-version }}
          body_path: CHANGELOG.md
          draft: false
          prerelease: false

